version: 2.1

jobs:
  environs:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      OSHT_LOCATION: /home/circleci/osht/osht.sh
      CLIENTIP_PLUGGABLE_ALLOW_LOOPBACK: 1
    working_directory: ~/project/t/environs
    steps:
      - checkout:
          path: ~/project
      - run: git clone https://github.com/coryb/osht ~/osht
      - run: echo OSHT_LOCATION=$OSHT_LOCATION
      - run:
          command: |
            for f in ./*.sh; do \
                $f ;\
            done

workflows:
  version: 2.1
  test:
    jobs:
      - environs
