version: 2.1

jobs:
  environs:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/coryb/osht ~/osht
            cd t/environs && OSHT_LOCATION=~/osht/osht.sh ./01-smoke.sh && OSHT_LOCATION=~/osht/osht.sh ./02*.sh && OSHT_LOCATION=~/osht/osht.sh ./03*.sh && OSHT_LOCATION=~/osht/osht.sh ./04*.sh && OSHT_LOCATION=~/osht/osht.sh ./05*.sh

workflows:
  version: 2.1
  test:
    jobs:
      - environs
