name: test-salt-package-from-obs
on: workflow_dispatch
jobs: 
  t: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: "Test salt"
        run: |
            PRIVILEGED_TESTS=1 dist/salt/test/start-container.sh
            set +x
            sleep 60 # let assets to download
            curl -s 127.0.0.1/rest/server | grep mirror.23media.com
            curl 127.0.0.1/download
