name: test-salt-package-from-obs
on: workflow_dispatch
jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Test salt"
        run: |
          PRIVILEGED_TESTS=1 bash -x dist/salt/test/start-container.sh || echo "return code=$?"
          docker exec -t mirrorcachesalted rcmirrorcache status
      - uses: juliangruber/sleep-action@v1
        with:
          time: 20s
      - name: "Check server"
        if: ${{ always() }}
        run: |
          curl -si 127.0.0.1:3000/rest/server || sleep 15
          curl -si 127.0.0.1:3000/rest/server || echo "return_code=$?"
          curl -s 127.0.0.1:3000/rest/server | grep -o mirror.23media.com
      - name: "Check download"
        run: |
          # we started EU geocluster node and 127.0.0.3 is defined from EU
          docker exec -t mirrorcachesalted curl --interface 127.0.0.3 -s 127.0.0.1:3000/download | grep repositories
      - name: "Check repositories"
        run: |
          docker exec -t mirrorcachesalted curl --interface 127.0.0.3 -sL 127.0.0.1:3000/repositories | grep '<tr>'
      - name: "Check logs"
        if: ${{ always() }}
        run: |
          docker exec -t mirrorcachesalted journalctl -xn200 --no-pager -u mirrorcache
      - name: "Apply state once again"
        run: |
          docker exec -t mirrorcachesalted salt-call --local state.apply -l debug 'profile/mirrorcache/services'
